name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Build and push Docker image
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_IMAGE_REPOSITORY: ${{ secrets.DOCKERHUB_IMAGE_REPOSITORY }}
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: "$DOCKERHUB_USERNAME/$DOCKERHUB_IMAGE_REPOSITORY:latest"
        
        
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Setup SSH
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_SERVER_IP: ${{ secrets.SSH_SERVER_IP }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        echo "$SSH_SERVER_IP ecdsa-sha2-nistp256 $(ssh-keyscan $SSH_SERVER_IP 2>/dev/null)" > ~/.ssh/known_hosts

    - name: Deploy Discord Bot
      env:
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        STRATZ_TOKEN: ${{ secrets.STRATZ_TOKEN }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        SSH_SERVER_USER: ${{ secrets.SSH_SERVER_USER }}
        SSH_SERVER_IP: ${{ secrets.SSH_SERVER_IP }}
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_IMAGE_REPOSITORY: ${{ secrets.DOCKERHUB_IMAGE_REPOSITORY }}
      run: |
        ssh $SSH_SERVER_USER@$SSH_SERVER_IP "docker pull $DOCKERHUB_USERNAME/$DOCKERHUB_CONTAINER_REGISTRY:latest"
        ssh $SSH_SERVER_USER@$SSH_SERVER_IP "docker stop feigbot || true"
        ssh $SSH_SERVER_USER@$SSH_SERVER_IP "docker rm feigbot || true"
        ssh $SSH_SERVER_USER@$SSH_SERVER_IP "docker run -d -p 8000:8000 --name feigbot -e DISCORD_TOKEN=$DISCORD_TOKEN \ -e STRATZ_TOKEN=$STRATZ_TOKEN \ -e OPENAI_API_KEY=$OPENAI_API_KEY $DOCKERHUB_USERNAME/$DOCKERHUB_IMAGE_REPOSITORY:latest"
