name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}  
    
    - name: Build and push Docker image
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_IMAGE_REPOSITORY: ${{ secrets.DOCKERHUB_IMAGE_REPOSITORY }}
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: zanmato1106/feigbot-images:latest
        
        
  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      
    - name: Setup SSH
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_SERVER_IP: ${{ secrets.SSH_SERVER_IP }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        echo "$SSH_SERVER_IP ecdsa-sha2-nistp256 $(ssh-keyscan $SSH_SERVER_IP 2>/dev/null)" > ~/.ssh/known_hosts

    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_SERVER_IP }}
        username: ${{ secrets.SSH_SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_IMAGE_REPOSITORY }}:latest
          docker stop feigbot || true
          docker rm feigbot || true
          sudo docker run -d -p 8000:8000 -e DISCORD_TOKEN='${{ secrets.DISCORD_TOKEN }}' -e UBERDUCK_API_KEY='${{ secrets.UBERDUCK_API_KEY }}' -e UBERDUCK_API_SECRET='${{ secrets.UBERDUCK_API_SECRET }}' -e STRATZ_TOKEN='${{ secrets.STRATZ_TOKEN }}' -e OPENAI_API_KEY='${{ secrets.OPENAI_API_KEY }}' --privileged fg -v /log:/log --name feigbot zanmato1106/feigbot-images:latest
